spring:
  application:
    name: recommendation-service
  datasource:
    url: jdbc:h2:mem:company-db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-company
  sql:
    init:
      mode: always
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/